-- Migration 001: Core users table
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  is_admin BOOLEAN NOT NULL DEFAULT FALSE
);
