/**
 * Slack integration for Contrax — bid-match alerts delivered as rich Slack
 * Block Kit messages via Incoming Webhooks.
 *
 * A user connects a Slack Incoming Webhook URL (from Slack's "Incoming
 * Webhooks" app, https://api.slack.com/messaging/webhooks) in
 * Settings → Integrations. When generateBidAlerts() matches a new bid to
 * their profile, a formatted Block Kit message is POSTed to that channel —
 * alongside the generic webhook delivery in src/lib/webhooks.ts.
 *
 * Design (mirrors webhooks.ts): fire-and-log, no queue. Every delivery
 * attempt is logged to `slack_deliveries` with the HTTP status Slack
 * returned. Transient failures (5xx/timeouts/network) retry ONCE; 4xx
 * (bad URL, channel removed, invalid token) is never retried. The
 * enable/disable toggle is independent from the generic webhooks — a user
 * can pause Slack alerts while keeping their Zapier endpoints active.
 *
 * Runtime note: like src/lib/webhooks.ts, this module must stay free of
 * `node:` imports — it is imported from src/lib/bid-alerts.ts, which is
 * reachable from client route files (via alerts.tsx). fetch + Web Crypto
 * are available in Node 19+ (Vercel), Bun, and browsers.
 */
import { sql } from "~/db";
import type { BidMatchEvent } from "./webhooks";

export interface SlackConfig {
  user_id: number;
  webhook_url: string;
  enabled: boolean;
  created_at: string;
  updated_at: string;
  /** Populated by getSlackConfig() only. */
  last_delivery?: SlackDelivery | null;
}

export interface SlackDelivery {
  id: number;
  user_id: number;
  event: string;
  status_code: number | null;
  attempt: number;
  success: boolean;
  error: string | null;
  created_at: string;
}

const TIMEOUT_MS = 10_000;

// ── Table helpers ────────────────────────────────────────────────────────────
export async function ensureSlackTables() {
  await sql()`CREATE TABLE IF NOT EXISTS slack_config (
    user_id INTEGER PRIMARY KEY REFERENCES users(id),
    webhook_url TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`;
  await sql()`CREATE TABLE IF NOT EXISTS slack_deliveries (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    event TEXT NOT NULL,
    status_code INTEGER,
    attempt INTEGER NOT NULL DEFAULT 1,
    success BOOLEAN NOT NULL DEFAULT false,
    error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`;
  await sql()`CREATE INDEX IF NOT EXISTS slack_deliveries_user_id_idx ON slack_deliveries (user_id, created_at DESC)`;
}

// ── Helpers ──────────────────────────────────────────────────────────────────
function toBool(value: unknown): boolean {
  return value === true || value === "true" || value === 1 || value === "1";
}

function toSlackConfig(row: any): SlackConfig {
  return {
    user_id: Number(row.user_id),
    webhook_url: String(row.webhook_url || ""),
    enabled: toBool(row.enabled),
    created_at: String(row.created_at),
    updated_at: String(row.updated_at),
  };
}

function toSlackDelivery(row: any): SlackDelivery {
  return {
    id: Number(row.id),
    user_id: Number(row.user_id),
    event: String(row.event),
    status_code: row.status_code == null ? null : Number(row.status_code),
    attempt: Number(row.attempt),
    success: toBool(row.success),
    error: row.error == null ? null : String(row.error),
    created_at: String(row.created_at),
  };
}

/**
 * Slack Incoming Webhook URLs look like
 * long https URLs on the hooks.slack.com host (create one at slack.com/apps
 * → Incoming Webhooks).
 */
export function isValidSlackWebhookUrl(url: string): boolean {
  try {
    const parsed = new URL(url);
    if (parsed.protocol !== "https:") return false;
    const host = parsed.hostname.toLowerCase();
    return host === "hooks.slack.com" || host.endsWith(".slack.com");
  } catch {
    return false;
  }
}

/**
 * The base URL Contrax links back to ("Open in Contrax"). Server-side this is
 * the production URL (PUBLIC_URL override supported); in a browser the origin
 * is correct by construction. NODE_ENV is deliberately NOT consulted — bid
 * alerts are generated by the GitHub Actions runner where NODE_ENV is unset,
 * and the production URL is the only sensible link target there.
 */
export function slackAppUrl(): string {
  if (typeof window !== "undefined") return window.location.origin;
  return process.env.PUBLIC_URL || "https://www.contrax.company";
}

// ── CRUD ─────────────────────────────────────────────────────────────────────
/** Load a user's Slack config (with latest delivery status), or null. */
export async function getSlackConfig(userId: number): Promise<SlackConfig | null> {
  await ensureSlackTables();
  const rows = await sql()`SELECT user_id, webhook_url, enabled, created_at, updated_at
    FROM slack_config WHERE user_id = ${userId} LIMIT 1`;
  if (!rows.length) return null;
  const config = toSlackConfig(rows[0]);
  const deliveries = await sql()`SELECT id, user_id, event, status_code, attempt, success, error, created_at
    FROM slack_deliveries WHERE user_id = ${userId} ORDER BY created_at DESC LIMIT 1`;
  if (deliveries.length) config.last_delivery = toSlackDelivery(deliveries[0]);
  return config;
}

/** Upsert a user's Slack webhook URL (connecting implies enabling alerts). */
export async function saveSlackConfig(userId: number, webhookUrl: string, enabled: boolean): Promise<SlackConfig> {
  await ensureSlackTables();
  const url = String(webhookUrl || "").trim();
  if (!url) throw new Error("Slack webhook URL is required.");
  if (!isValidSlackWebhookUrl(url)) {
    throw new Error("That doesn't look like a Slack Incoming Webhook URL — Slack webhook URLs are https URLs on the hooks.slack.com domain (see the setup steps above).");
  }
  const rows = await sql()`
    INSERT INTO slack_config (user_id, webhook_url, enabled, updated_at)
    VALUES (${userId}, ${url}, ${enabled}, NOW())
    ON CONFLICT (user_id) DO UPDATE
      SET webhook_url = EXCLUDED.webhook_url, enabled = EXCLUDED.enabled, updated_at = NOW()
    RETURNING user_id, webhook_url, enabled, created_at, updated_at`;
  if (!rows.length) throw new Error("Failed to save Slack configuration.");
  return toSlackConfig(rows[0]);
}

/** Flip the enabled toggle without touching the stored URL. */
export async function setSlackEnabled(userId: number, enabled: boolean): Promise<SlackConfig | null> {
  await ensureSlackTables();
  const rows = await sql()`UPDATE slack_config SET enabled = ${enabled}, updated_at = NOW()
    WHERE user_id = ${userId}
    RETURNING user_id, webhook_url, enabled, created_at, updated_at`;
  if (!rows.length) return null;
  return toSlackConfig(rows[0]);
}

/** Remove the user's Slack connection entirely. */
export async function disconnectSlack(userId: number): Promise<boolean> {
  await ensureSlackTables();
  const rows = await sql()`DELETE FROM slack_config WHERE user_id = ${userId} RETURNING user_id`;
  return rows.length > 0;
}

// ── Block Kit formatting ─────────────────────────────────────────────────────
/** Set-aside badge: colored emoji prefix + short label, matching SBA programs. */
export function setAsideBadge(setAside: string | null): { emoji: string; label: string } {
  const s = String(setAside || "");
  const patterns: Array<{ match: RegExp; emoji: string; label: string }> = [
    { match: /8\s*\(?\s*a\s*\)?/i, emoji: "🟣", label: "8(a)" },
    { match: /sdvosb/i, emoji: "🔵", label: "SDVOSB" },
    { match: /edwosb|wosb/i, emoji: "🟢", label: "WOSB" },
    { match: /hubzone/i, emoji: "🟡", label: "HUBZone" },
  ];
  for (const p of patterns) {
    if (p.match.test(s)) return { emoji: p.emoji, label: p.label };
  }
  return { emoji: "⚪", label: s || "Set-aside" };
}

/** Escape Slack mrkdwn metacharacters in untrusted text. */
function escapeMrkdwn(text: string): string {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function formatDueDate(value: string | null): string {
  if (!value) return "No due date listed";
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return String(value);
  return d.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  });
}

function formatMatchedOn(matchedOn: string[]): string {
  const labels: Record<string, string> = {
    set_aside: "set-aside",
    naics: "NAICS",
    category: "category",
  };
  const parts = matchedOn.map((m) => labels[m] ?? m.replace(/_/g, " "));
  return parts.length ? parts.join(", ") : "your profile";
}

/**
 * Build the Block Kit payload for a bid match alert. Compact and
 * mobile-friendly: a header, a scannable section (badge, title, agency,
 * location/due date, set-aside + match reasons), and link actions to the
 * source RFP and the Contrax app.
 */
export function buildBidMatchSlackBlocks(event: BidMatchEvent, appUrl: string) {
  const badge = setAsideBadge(event.bid.set_aside);
  const title = event.bid.title || "Untitled opportunity";
  const agency = event.bid.agency || "";
  const location = event.bid.location || "Location not listed";
  const due = formatDueDate(event.bid.due_date);
  const setAside = badge.label;
  const matched = formatMatchedOn(event.matchedOn);

  const bodyText =
    `*${badge.emoji} ${escapeMrkdwn(badge.label)}*  *${escapeMrkdwn(title)}*` +
    (agency ? `\n${escapeMrkdwn(agency)}` : "") +
    `\n📍 ${escapeMrkdwn(location)}  ·  Due: ${escapeMrkdwn(due)}` +
    `\nSet-aside: ${escapeMrkdwn(setAside)}  ·  Matched: ${escapeMrkdwn(matched)}`;

  const blocks: any[] = [
    { type: "header", text: { type: "plain_text", text: "🔔 New bid match for your profile" } },
    { type: "section", text: { type: "mrkdwn", text: bodyText } },
  ];

  const linkText = event.bid.source_url
    ? `<${event.bid.source_url}|View full RFP on SAM.gov>  |  <${appUrl}|Open in Contrax>`
    : `<${appUrl}|Open in Contrax>`;
  blocks.push({ type: "section", text: { type: "mrkdwn", text: linkText } });

  return { blocks };
}

// ── Delivery ─────────────────────────────────────────────────────────────────
function logDelivery(input: {
  userId: number;
  event: string;
  statusCode: number | null;
  attempt: number;
  success: boolean;
  error: string | null;
}) {
  return sql()`INSERT INTO slack_deliveries (user_id, event, status_code, attempt, success, error)
    VALUES (${input.userId}, ${input.event}, ${input.statusCode}, ${input.attempt}, ${input.success}, ${input.error})`;
}

/** One POST attempt to a Slack incoming webhook. Resolves { statusCode, error }. */
async function postOnce(
  url: string,
  payload: unknown,
): Promise<{ statusCode: number | null; error: string | null }> {
  try {
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "User-Agent": "Contrax-Slack/1.0",
      },
      body: JSON.stringify(payload),
      signal: AbortSignal.timeout(TIMEOUT_MS),
    });
    if (res.ok) return { statusCode: res.status, error: null };
    // Slack returns a text body explaining the error (e.g. "invalid_token").
    const text = await res.text().catch(() => "");
    return { statusCode: res.status, error: text ? `Slack: ${text.slice(0, 200)}` : `HTTP ${res.status}` };
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return { statusCode: null, error: `Request failed: ${msg}` };
  }
}

/**
 * Deliver one message to a Slack webhook. Retries ONCE on
 * 5xx/timeout/network failure; 2xx and 4xx are never retried (4xx means the
 * URL/token/channel is bad — retrying cannot help). Every attempt is logged
 * to slack_deliveries. Never throws — delivery failures are recorded, not
 * propagated (bid sync must not fail because Slack is unreachable).
 */
export async function deliverSlackMessage(
  config: Pick<SlackConfig, "user_id" | "webhook_url">,
  event: string,
  payload: unknown,
): Promise<{ delivered: boolean; attempts: number; statusCode: number | null }> {
  try {
    let result = await postOnce(config.webhook_url, payload);
    const status = result.statusCode ?? 0;
    // 2xx → success. 4xx → client error, no retry. 5xx/timeout/network → retry once.
    if (status >= 200 && status < 300) {
      await logDelivery({ userId: config.user_id, event, statusCode: status, attempt: 1, success: true, error: null });
      return { delivered: true, attempts: 1, statusCode: status };
    }
    if (status >= 400 && status < 500) {
      await logDelivery({ userId: config.user_id, event, statusCode: status, attempt: 1, success: false, error: result.error });
      return { delivered: false, attempts: 1, statusCode: status };
    }
    await logDelivery({ userId: config.user_id, event, statusCode: status, attempt: 1, success: false, error: result.error });
    result = await postOnce(config.webhook_url, payload);
    const status2 = result.statusCode ?? 0;
    const success2 = status2 >= 200 && status2 < 300;
    await logDelivery({
      userId: config.user_id, event,
      statusCode: status2, attempt: 2, success: success2, error: result.error,
    });
    return { delivered: success2, attempts: 2, statusCode: status2 };
  } catch (e) {
    console.error(`[slack] deliver for user ${config.user_id} crashed:`, e instanceof Error ? e.message : e);
    return { delivered: false, attempts: 0, statusCode: null };
  }
}

/**
 * Fire Slack bid-match alerts for every user who received a new bid alert and
 * has Slack connected + enabled. Loads configs once, then delivers
 * (fire-and-log, sequential). Returns the number of messages attempted.
 * Never throws. Called from generateBidAlerts() alongside
 * fireBidMatchWebhooks().
 */
export async function fireSlackBidMatchAlerts(events: BidMatchEvent[]): Promise<number> {
  if (!events.length) return 0;
  const userIds = [...new Set(events.map((e) => e.userId))];
  let configs: SlackConfig[] = [];
  try {
    await ensureSlackTables();
    const rows = await sql()`SELECT user_id, webhook_url, enabled, created_at, updated_at
      FROM slack_config WHERE enabled = true AND user_id = ANY(${userIds})`;
    configs = (rows as any[]).map(toSlackConfig);
  } catch (e) {
    console.error("[slack] failed to load slack configs:", e instanceof Error ? e.message : e);
    return 0;
  }
  if (!configs.length) return 0;
  const byUser = new Map(configs.map((c) => [c.user_id, c]));
  const appUrl = slackAppUrl();
  let attempted = 0;
  for (const event of events) {
    const config = byUser.get(event.userId);
    if (!config) continue;
    attempted++;
    const payload = buildBidMatchSlackBlocks(event, appUrl);
    await deliverSlackMessage(config, "bid_match", payload);
  }
  return attempted;
}

// ── Test message ─────────────────────────────────────────────────────────────
/**
 * Send a sample bid-match message so the user can verify the channel
 * immediately after connecting. Returns the delivery outcome (or null when no
 * Slack connection exists).
 */
export async function sendSlackTest(
  userId: number,
): Promise<{ config: SlackConfig; delivered: boolean; attempts: number; statusCode: number | null } | null> {
  await ensureSlackTables();
  const config = await getSlackConfig(userId);
  if (!config) return null;
  const event: BidMatchEvent = {
    userId,
    bid: {
      title: "TEST — Janitorial Services for Federal Building (Sample Match)",
      agency: "General Services Administration",
      set_aside: "8(a) Set-Aside (Competitive)",
      location: "Washington, DC",
      due_date: new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10),
      source_url: "https://sam.gov/opp/sample-test",
    },
    matchedOn: ["set_aside", "naics"],
  };
  const payload = buildBidMatchSlackBlocks(event, slackAppUrl());
  const outcome = await deliverSlackMessage(config, "bid_match", payload);
  return { config, ...outcome };
}
