import { createFileRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";
import { useEffect, useState, type ChangeEvent } from "react";
import { getCurrentUser } from "~/lib/auth";
import { TrialGate, PlanGate } from "~/components/TrialGate";
import { evaluateProposal, type ProposalEvaluation } from "~/lib/evaluator";
import { sql } from "~/db";

const loadBids = createServerFn({ method: "GET" }).handler(async () => {
  const user = await getCurrentUser(); if (!user) return [];
  try { await sql()`CREATE TABLE IF NOT EXISTS tracked_bids (id SERIAL PRIMARY KEY, user_email TEXT NOT NULL, bid_id TEXT NOT NULL, bid_title TEXT NOT NULL, agency TEXT NOT NULL, due_date TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'tracked', last_checked TIMESTAMPTZ DEFAULT NOW(), created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(user_email, bid_id))`; const rows = await sql()`SELECT bid_id, bid_title, agency FROM tracked_bids WHERE user_email = ${user.email} ORDER BY due_date ASC`; return rows as { bid_id: string; bid_title: string; agency: string }[]; } catch { return []; }
});
const runEvaluation = createServerFn({ method: "POST" }).validator((d: unknown) => { const x = d as { rfp?: string; proposal?: string }; if (!x.rfp?.trim() || !x.proposal?.trim()) throw new Error("RFP and proposal are required"); return { rfp: x.rfp.trim(), proposal: x.proposal.trim() }; }).handler(async ({ data }) => { if (!(await getCurrentUser())) throw new Error("Not authenticated"); return evaluateProposal(data.rfp, data.proposal); });
export const Route = createFileRoute("/evaluate")({ loader: () => getCurrentUser(), component: EvaluatePage, head: () => ({ meta: [{ title: "Proposal Evaluator — Section M Scoring | Contrax" }, { name: "description", content: "Score your government proposal draft against the RFP's Section M evaluation criteria with Contrax AI." }] }) });
function EvaluatePage() { const user = Route.useLoaderData(); if (!user) return <div className="min-h-screen bg-slate-950 p-10 text-white"><h1 className="text-4xl font-bold">Proposal Evaluator</h1><p className="mt-4">Sign in to evaluate a proposal draft.</p><a className="mt-6 inline-block rounded-lg bg-amber-500 px-5 py-3 font-semibold" href="/login">Sign in →</a></div>; return <TrialGate><PlanGate featureName="Proposal Evaluator"><Evaluator /></PlanGate></TrialGate>; }
function Evaluator() { const [bids, setBids] = useState<{bid_id:string;bid_title:string;agency:string}[]>([]); const [rfp, setRfp] = useState(""); const [proposal, setProposal] = useState(""); const [result, setResult] = useState<ProposalEvaluation | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); useEffect(() => { loadBids().then(setBids).catch(() => {}); }, []);
 const submit = async () => { setError(""); setLoading(true); try { setResult(await runEvaluation({ data: { rfp, proposal } })); } catch (e) { setError(e instanceof Error ? e.message : "Evaluation failed"); } finally { setLoading(false); } };
 const readFile = async (e: ChangeEvent<HTMLInputElement>) => { const file=e.target.files?.[0]; if (!file) return; if (file.type === "text/plain" || file.name.endsWith(".txt")) setProposal(await file.text()); else setError("PDF/DOCX files must be pasted as text in this version."); };
 return <div className="min-h-screen bg-slate-50"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4"><a href="/dashboard" className="font-bold text-slate-900">← Dashboard</a><span className="font-semibold text-blue-700">Contrax</span></div></header><main className="mx-auto max-w-6xl px-4 py-10"><div className="mb-8"><p className="text-sm font-semibold uppercase tracking-wider text-blue-600">Section M analysis</p><h1 className="mt-2 text-3xl font-bold text-slate-900 sm:text-4xl">📋 Proposal Evaluator</h1><p className="mt-3 max-w-2xl text-slate-600">See your draft through a government evaluator's eyes before you submit.</p></div><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold text-slate-900">1. RFP / solicitation</h2><select className="mt-4 w-full rounded-lg border border-slate-300 p-3 text-sm" defaultValue="" onChange={e=>{const b=bids.find(x=>x.bid_id===e.target.value); if(b) setRfp(`${b.bid_title}\nAgency: ${b.agency}`)}}><option value="">Select a tracked bid (optional)</option>{bids.map(b=><option key={b.bid_id} value={b.bid_id}>{b.bid_title} — {b.agency}</option>)}</select><textarea value={rfp} onChange={e=>setRfp(e.target.value)} rows={13} placeholder="Paste the RFP, especially Section M evaluation criteria..." className="mt-3 w-full rounded-lg border border-slate-300 p-3 text-sm focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold text-slate-900">2. Proposal draft</h2><textarea value={proposal} onChange={e=>setProposal(e.target.value)} rows={13} placeholder="Paste your proposal draft here..." className="mt-4 w-full rounded-lg border border-slate-300 p-3 text-sm focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /><label className="mt-3 inline-flex cursor-pointer rounded-lg border border-slate-300 px-3 py-2 text-sm font-medium text-slate-600 hover:bg-slate-50">Upload .txt / .pdf / .docx<input type="file" accept=".txt,.pdf,.docx" onChange={readFile} className="hidden" /></label></section></div><button disabled={loading} onClick={submit} className="mt-6 w-full rounded-xl bg-blue-600 px-6 py-4 font-bold text-white shadow-sm hover:bg-blue-700 disabled:cursor-wait disabled:opacity-60">{loading ? "⏳ Evaluating against Section M..." : "Evaluate Proposal →"}</button>{error&&<p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{result&&<Results result={result}/>}</main></div> }
function Results({result:r}:{result:ProposalEvaluation}) { const tone=(s:string)=>s==="strong"?"text-green-700 bg-green-50":s==="adequate"?"text-amber-700 bg-amber-50": "text-red-700 bg-red-50"; return <div className="mt-10 space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Overall score</h2><strong className="text-4xl text-blue-700">{r.overallScore}<span className="text-lg text-slate-400">/100</span></strong></div><div className="mt-4 h-4 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${r.overallScore}%`}}/></div></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Section M breakdown</h2><div className="mt-4 space-y-3">{r.criteria.map((c,i)=><div key={i} className="rounded-xl border border-slate-100 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><b>{c.status==="strong"?"🟢":c.status==="adequate"?"🟡":"🔴"} {c.name}</b><span className={`rounded-full px-2 py-1 text-xs font-bold ${tone(c.status)}`}>{c.score}/{c.maxScore} · {c.status}</span></div><p className="mt-2 text-sm text-slate-600">{c.feedback}</p></div>)}</div></section><Info title="Missing elements" items={r.missingElements}/><Info title="⚠️ Compliance risks" items={r.complianceRisks.map(x=>x.farClause?`${x.description} (${x.farClause})`:x.description)}/><Info title="Weak arguments" items={r.weakArguments}/><Info title="Recommendations" items={r.recommendations}/></div> }
function Info({title,items}:{title:string;items:string[]}) { return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">{title}</h2>{items.length?<ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-slate-600">{items.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p className="mt-3 text-sm text-slate-500">None identified.</p>}</section> }
